/*
 * Copyright (C) Imaging in Motion Associates LLC, 2015 - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 */

package com.iimassociates.cmsreporting.server.batch;

import com.iimassociates.cmsreporting.server.domain.Provider;
import com.iimassociates.cmsreporting.server.service.ProviderRepository;
import org.springframework.batch.item.data.RepositoryItemWriter;
import org.springframework.batch.item.file.FlatFileItemReader;
import org.springframework.batch.item.file.LineMapper;
import org.springframework.batch.item.file.mapping.DefaultLineMapper;
import org.springframework.batch.item.file.transform.DelimitedLineTokenizer;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.core.io.FileSystemResource;

@Configuration
public class ProviderBatch {

    @Value("${com.iimassociates.cmsreporting.input.directory}")
    private String inputDirectory;

    @Value("${com.iimassociates.cmsreporting.input.provider-filename}")
    private String providerFileName;

    @Bean
    public FlatFileItemReader<Provider> providerFileReader(LineMapper<Provider> providerLineMapper) {
        FlatFileItemReader<Provider> reader = new FlatFileItemReader<>();
        reader.setLineMapper(providerLineMapper);
        FileSystemResource fileSystemResource = new FileSystemResource(inputDirectory + "/" + providerFileName);
        reader.setResource(fileSystemResource);
        reader.setLinesToSkip(1);

        try {
            reader.afterPropertiesSet();
        } catch (Exception e) {
            e.printStackTrace();
        }

        return reader;
    }

    @Bean
    public LineMapper<Provider> providerLineMapper(DelimitedLineTokenizer providerLineTokenizer) {
        DefaultLineMapper<Provider> lineMapper = new DefaultLineMapper<>();
        lineMapper.setLineTokenizer(providerLineTokenizer);
        lineMapper.setFieldSetMapper(fieldSet -> {
            Provider provider = new Provider();
            provider.setNpi(fieldSet.readLong("npi"));
            provider.setEntityTypeCode("".equals(fieldSet.readString("entityTypeCode")) ? null : fieldSet.readInt("entityTypeCode"));
            provider.setReplacementNpi("".equals(fieldSet.readString("replacementNpi")) ? null : fieldSet.readLong("replacementNpi"));
            provider.setEmployerIdentificationNumber(fieldSet.readString("employerIdentificationNumber"));
            provider.setProviderOrganizationName(fieldSet.readString("providerOrganizationName"));
            provider.setProviderLastName(fieldSet.readString("providerLastName"));
            provider.setProviderFirstName(fieldSet.readString("providerFirstName"));
            provider.setProviderMiddleName(fieldSet.readString("providerMiddleName"));
            provider.setProviderNamePrefixText(fieldSet.readString("providerNamePrefixText"));
            provider.setProviderNameSuffixText(fieldSet.readString("providerNameSuffixText"));
            provider.setProviderCredentialText(fieldSet.readString("providerCredentialText"));
            provider.setProviderOtherOrganizationName(fieldSet.readString("providerOtherOrganizationName"));
            provider.setProviderOtherOrganizationNameTypeCode(fieldSet.readString("providerOtherOrganizationNameTypeCode"));
            provider.setProviderOtherLastName(fieldSet.readString("providerOtherLastName"));
            provider.setProviderOtherFirstName(fieldSet.readString("providerOtherFirstName"));
            provider.setProviderOtherMiddleName(fieldSet.readString("providerOtherMiddleName"));
            provider.setProviderOtherNamePrefixText(fieldSet.readString("providerOtherNamePrefixText"));
            provider.setProviderOtherNameSuffixText(fieldSet.readString("providerOtherNameSuffixText"));
            provider.setProviderOtherCredentialText(fieldSet.readString("providerOtherCredentialText"));
            provider.setProviderOtherLastNameTypeCode(fieldSet.readString("providerOtherLastNameTypeCode"));
            provider.setProviderFirstLineBusinessMailingAddress(fieldSet.readString("providerFirstLineBusinessMailingAddress"));
            provider.setProviderSecondLineBusinessMailingAddress(fieldSet.readString("providerSecondLineBusinessMailingAddress"));
            provider.setProviderBusinessMailingAddressCityName(fieldSet.readString("providerBusinessMailingAddressCityName"));
            provider.setProviderBusinessMailingAddressStateName(fieldSet.readString("providerBusinessMailingAddressStateName"));
            provider.setProviderBusinessMailingAddressPostalCode(fieldSet.readString("providerBusinessMailingAddressPostalCode"));
            provider.setProviderBusinessMailingAddressCountryCode(fieldSet.readString("providerBusinessMailingAddressCountryCode"));
            provider.setProviderBusinessMailingAddressTelephoneNumber(fieldSet.readString("providerBusinessMailingAddressTelephoneNumber"));
            provider.setProviderBusinessMailingAddressFaxNumber(fieldSet.readString("providerBusinessMailingAddressFaxNumber"));
            provider.setProviderFirstLineBusinessPracticeLocationAddress(fieldSet.readString("providerFirstLineBusinessPracticeLocationAddress"));
            provider.setProviderSecondLineBusinessPracticeLocationAddress(fieldSet.readString("providerSecondLineBusinessPracticeLocationAddress"));
            provider.setProviderBusinessPracticeLocationAddressCityName(fieldSet.readString("providerBusinessPracticeLocationAddressCityName"));
            provider.setProviderBusinessPracticeLocationAddressStateName(fieldSet.readString("providerBusinessPracticeLocationAddressStateName"));
            provider.setProviderBusinessPracticeLocationAddressPostalCode(fieldSet.readString("providerBusinessPracticeLocationAddressPostalCode"));
            provider.setProviderBusinessPracticeLocationAddressCountryCode(fieldSet.readString("providerBusinessPracticeLocationAddressCountryCode"));
            provider.setProviderBusinessPracticeLocationAddressTelephoneNumber(fieldSet.readString("providerBusinessPracticeLocationAddressTelephoneNumber"));
            provider.setProviderBusinessPracticeLocationAddressFaxNumber(fieldSet.readString("providerBusinessPracticeLocationAddressFaxNumber"));
            provider.setProviderEnumerationDate("".equals(fieldSet.readString("providerEnumerationDate")) ? null : fieldSet.readDate("providerEnumerationDate", "MM/dd/yyyy"));
            provider.setLastUpdateDate("".equals(fieldSet.readString("lastUpdateDate")) ? null : fieldSet.readDate("lastUpdateDate", "MM/dd/yyyy"));
            provider.setNpiDeactivationReasonCode(fieldSet.readString("npiDeactivationReasonCode"));
            provider.setDeactivationDate("".equals(fieldSet.readString("deactivationDate")) ? null : fieldSet.readDate("deactivationDate", "MM/dd/yyyy"));
            provider.setReactivationDate("".equals(fieldSet.readString("reactivationDate")) ? null : fieldSet.readDate("reactivationDate", "MM/dd/yyyy"));
            provider.setProviderGenderCode(fieldSet.readString("providerGenderCode"));
            provider.setAuthorizedOfficialLastName(fieldSet.readString("authorizedOfficialLastName"));
            provider.setAuthorizedOfficialLastName(fieldSet.readString("authorizedOfficialFirstName"));
            provider.setAuthorizedOfficialMiddleName(fieldSet.readString("authorizedOfficialMiddleName"));
            provider.setAuthorizedOfficialTitle(fieldSet.readString("authorizedOfficialTitle"));
            provider.setAuthorizedOfficialTelephoneNumber(fieldSet.readString("authorizedOfficialTelephoneNumber"));
            provider.setHealthcareProviderTaxonomyCode1(fieldSet.readString("healthcareProviderTaxonomyCode1"));
            provider.setProviderLicenseNumber1(fieldSet.readString("providerLicenseNumber1"));
            provider.setProviderLicenseNumberStateCode1(fieldSet.readString("providerLicenseNumberStateCode1"));
            provider.setHealthcareProviderPrimaryTaxonomySwitch1(fieldSet.readString("healthcareProviderPrimaryTaxonomySwitch1"));
            provider.setHealthcareProviderTaxonomyCode2(fieldSet.readString("healthcareProviderTaxonomyCode2"));
            provider.setProviderLicenseNumber2(fieldSet.readString("providerLicenseNumber2"));
            provider.setProviderLicenseNumberStateCode2(fieldSet.readString("providerLicenseNumberStateCode2"));
            provider.setHealthcareProviderPrimaryTaxonomySwitch2(fieldSet.readString("healthcareProviderPrimaryTaxonomySwitch2"));
            provider.setHealthcareProviderTaxonomyCode3(fieldSet.readString("healthcareProviderTaxonomyCode3"));
            provider.setProviderLicenseNumber3(fieldSet.readString("providerLicenseNumber3"));
            provider.setProviderLicenseNumberStateCode3(fieldSet.readString("providerLicenseNumberStateCode3"));
            provider.setHealthcareProviderPrimaryTaxonomySwitch3(fieldSet.readString("healthcareProviderPrimaryTaxonomySwitch3"));
            provider.setHealthcareProviderTaxonomyCode4(fieldSet.readString("healthcareProviderTaxonomyCode4"));
            provider.setProviderLicenseNumber4(fieldSet.readString("providerLicenseNumber4"));
            provider.setProviderLicenseNumberStateCode4(fieldSet.readString("providerLicenseNumberStateCode4"));
            provider.setHealthcareProviderPrimaryTaxonomySwitch4(fieldSet.readString("healthcareProviderPrimaryTaxonomySwitch4"));
            provider.setHealthcareProviderTaxonomyCode5(fieldSet.readString("healthcareProviderTaxonomyCode5"));
            provider.setProviderLicenseNumber5(fieldSet.readString("providerLicenseNumber5"));
            provider.setProviderLicenseNumberStateCode5(fieldSet.readString("providerLicenseNumberStateCode5"));
            provider.setHealthcareProviderPrimaryTaxonomySwitch5(fieldSet.readString("healthcareProviderPrimaryTaxonomySwitch5"));
            provider.setHealthcareProviderTaxonomyCode6(fieldSet.readString("healthcareProviderTaxonomyCode6"));
            provider.setProviderLicenseNumber6(fieldSet.readString("providerLicenseNumber6"));
            provider.setProviderLicenseNumberStateCode6(fieldSet.readString("providerLicenseNumberStateCode6"));
            provider.setHealthcareProviderPrimaryTaxonomySwitch7(fieldSet.readString("healthcareProviderPrimaryTaxonomySwitch7"));
            provider.setHealthcareProviderTaxonomyCode8(fieldSet.readString("healthcareProviderTaxonomyCode8"));
            provider.setProviderLicenseNumber8(fieldSet.readString("providerLicenseNumber8"));
            provider.setProviderLicenseNumberStateCode8(fieldSet.readString("providerLicenseNumberStateCode8"));
            provider.setHealthcareProviderPrimaryTaxonomySwitch8(fieldSet.readString("healthcareProviderPrimaryTaxonomySwitch8"));
            provider.setHealthcareProviderTaxonomyCode9(fieldSet.readString("healthcareProviderTaxonomyCode9"));
            provider.setProviderLicenseNumber9(fieldSet.readString("providerLicenseNumber9"));
            provider.setProviderLicenseNumberStateCode9(fieldSet.readString("providerLicenseNumberStateCode9"));
            provider.setHealthcareProviderPrimaryTaxonomySwitch9(fieldSet.readString("healthcareProviderPrimaryTaxonomySwitch9"));
            provider.setHealthcareProviderTaxonomyCode10(fieldSet.readString("healthcareProviderTaxonomyCode10"));
            provider.setProviderLicenseNumber10(fieldSet.readString("providerLicenseNumber10"));
            provider.setProviderLicenseNumberStateCode10(fieldSet.readString("providerLicenseNumberStateCode10"));
            provider.setHealthcareProviderPrimaryTaxonomySwitch10(fieldSet.readString("healthcareProviderPrimaryTaxonomySwitch10"));
            provider.setHealthcareProviderTaxonomyCode11(fieldSet.readString("healthcareProviderTaxonomyCode11"));
            provider.setProviderLicenseNumber11(fieldSet.readString("providerLicenseNumber11"));
            provider.setProviderLicenseNumberStateCode11(fieldSet.readString("providerLicenseNumberStateCode11"));
            provider.setHealthcareProviderPrimaryTaxonomySwitch11(fieldSet.readString("healthcareProviderPrimaryTaxonomySwitch11"));
            provider.setHealthcareProviderTaxonomyCode12(fieldSet.readString("healthcareProviderTaxonomyCode12"));
            provider.setProviderLicenseNumber12(fieldSet.readString("providerLicenseNumber12"));
            provider.setProviderLicenseNumberStateCode12(fieldSet.readString("providerLicenseNumberStateCode12"));
            provider.setHealthcareProviderPrimaryTaxonomySwitch12(fieldSet.readString("healthcareProviderPrimaryTaxonomySwitch12"));
            provider.setHealthcareProviderTaxonomyCode13(fieldSet.readString("healthcareProviderTaxonomyCode13"));
            provider.setProviderLicenseNumber13(fieldSet.readString("providerLicenseNumber13"));
            provider.setProviderLicenseNumberStateCode13(fieldSet.readString("providerLicenseNumberStateCode13"));
            provider.setHealthcareProviderPrimaryTaxonomySwitch13(fieldSet.readString("healthcareProviderPrimaryTaxonomySwitch13"));
            provider.setHealthcareProviderTaxonomyCode14(fieldSet.readString("healthcareProviderTaxonomyCode14"));
            provider.setProviderLicenseNumber14(fieldSet.readString("providerLicenseNumber14"));
            provider.setProviderLicenseNumberStateCode14(fieldSet.readString("providerLicenseNumberStateCode14"));
            provider.setHealthcareProviderPrimaryTaxonomySwitch14(fieldSet.readString("healthcareProviderPrimaryTaxonomySwitch14"));
            provider.setHealthcareProviderTaxonomyCode15(fieldSet.readString("healthcareProviderTaxonomyCode15"));
            provider.setProviderLicenseNumber15(fieldSet.readString("providerLicenseNumber15"));
            provider.setProviderLicenseNumberStateCode15(fieldSet.readString("providerLicenseNumberStateCode15"));
            provider.setHealthcareProviderPrimaryTaxonomySwitch15(fieldSet.readString("healthcareProviderPrimaryTaxonomySwitch15"));
            provider.setOtherProviderIdentifier1(fieldSet.readString("otherProviderIdentifier1"));
            provider.setOtherProviderIdentifierTypeCode1(fieldSet.readString("otherProviderIdentifierTypeCode1"));
            provider.setOtherProviderIdentifierState1(fieldSet.readString("otherProviderIdentifierState1"));
            provider.setOtherProviderIdentifierIssuer1(fieldSet.readString("otherProviderIdentifierIssuer1"));
            provider.setOtherProviderIdentifier2(fieldSet.readString("otherProviderIdentifier2"));
            provider.setOtherProviderIdentifierTypeCode2(fieldSet.readString("otherProviderIdentifierTypeCode2"));
            provider.setOtherProviderIdentifierState2(fieldSet.readString("otherProviderIdentifierState2"));
            provider.setOtherProviderIdentifierIssuer2(fieldSet.readString("otherProviderIdentifierIssuer2"));
            provider.setOtherProviderIdentifier3(fieldSet.readString("otherProviderIdentifier3"));
            provider.setOtherProviderIdentifierTypeCode3(fieldSet.readString("otherProviderIdentifierTypeCode3"));
            provider.setOtherProviderIdentifierState3(fieldSet.readString("otherProviderIdentifierState3"));
            provider.setOtherProviderIdentifierIssuer3(fieldSet.readString("otherProviderIdentifierIssuer3"));
            provider.setOtherProviderIdentifier4(fieldSet.readString("otherProviderIdentifier4"));
            provider.setOtherProviderIdentifierTypeCode4(fieldSet.readString("otherProviderIdentifierTypeCode4"));
            provider.setOtherProviderIdentifierState4(fieldSet.readString("otherProviderIdentifierState4"));
            provider.setOtherProviderIdentifierIssuer4(fieldSet.readString("otherProviderIdentifierIssuer4"));
            provider.setOtherProviderIdentifier5(fieldSet.readString("otherProviderIdentifier5"));
            provider.setOtherProviderIdentifierTypeCode5(fieldSet.readString("otherProviderIdentifierTypeCode5"));
            provider.setOtherProviderIdentifierState5(fieldSet.readString("otherProviderIdentifierState5"));
            provider.setOtherProviderIdentifierIssuer5(fieldSet.readString("otherProviderIdentifierIssuer5"));
            provider.setOtherProviderIdentifier6(fieldSet.readString("otherProviderIdentifier6"));
            provider.setOtherProviderIdentifierTypeCode6(fieldSet.readString("otherProviderIdentifierTypeCode6"));
            provider.setOtherProviderIdentifierState6(fieldSet.readString("otherProviderIdentifierState6"));
            provider.setOtherProviderIdentifierIssuer6(fieldSet.readString("otherProviderIdentifierIssuer6"));
            provider.setOtherProviderIdentifier7(fieldSet.readString("otherProviderIdentifier7"));
            provider.setOtherProviderIdentifierTypeCode7(fieldSet.readString("otherProviderIdentifierTypeCode7"));
            provider.setOtherProviderIdentifierState7(fieldSet.readString("otherProviderIdentifierState7"));
            provider.setOtherProviderIdentifierIssuer7(fieldSet.readString("otherProviderIdentifierIssuer7"));
            provider.setOtherProviderIdentifier8(fieldSet.readString("otherProviderIdentifier8"));
            provider.setOtherProviderIdentifierTypeCode8(fieldSet.readString("otherProviderIdentifierTypeCode8"));
            provider.setOtherProviderIdentifierState8(fieldSet.readString("otherProviderIdentifierState8"));
            provider.setOtherProviderIdentifierIssuer8(fieldSet.readString("otherProviderIdentifierIssuer8"));
            provider.setOtherProviderIdentifier9(fieldSet.readString("otherProviderIdentifier9"));
            provider.setOtherProviderIdentifierTypeCode9(fieldSet.readString("otherProviderIdentifierTypeCode9"));
            provider.setOtherProviderIdentifierState9(fieldSet.readString("otherProviderIdentifierState9"));
            provider.setOtherProviderIdentifierIssuer9(fieldSet.readString("otherProviderIdentifierIssuer9"));
            provider.setOtherProviderIdentifier10(fieldSet.readString("otherProviderIdentifier10"));
            provider.setOtherProviderIdentifierTypeCode10(fieldSet.readString("otherProviderIdentifierTypeCode10"));
            provider.setOtherProviderIdentifierState10(fieldSet.readString("otherProviderIdentifierState10"));
            provider.setOtherProviderIdentifierIssuer10(fieldSet.readString("otherProviderIdentifierIssuer10"));
            provider.setOtherProviderIdentifier11(fieldSet.readString("otherProviderIdentifier11"));
            provider.setOtherProviderIdentifierTypeCode11(fieldSet.readString("otherProviderIdentifierTypeCode11"));
            provider.setOtherProviderIdentifierState11(fieldSet.readString("otherProviderIdentifierState11"));
            provider.setOtherProviderIdentifierIssuer11(fieldSet.readString("otherProviderIdentifierIssuer11"));
            provider.setOtherProviderIdentifier12(fieldSet.readString("otherProviderIdentifier12"));
            provider.setOtherProviderIdentifierTypeCode12(fieldSet.readString("otherProviderIdentifierTypeCode12"));
            provider.setOtherProviderIdentifierState12(fieldSet.readString("otherProviderIdentifierState12"));
            provider.setOtherProviderIdentifierIssuer12(fieldSet.readString("otherProviderIdentifierIssuer12"));
            provider.setOtherProviderIdentifier13(fieldSet.readString("otherProviderIdentifier13"));
            provider.setOtherProviderIdentifierTypeCode13(fieldSet.readString("otherProviderIdentifierTypeCode13"));
            provider.setOtherProviderIdentifierState13(fieldSet.readString("otherProviderIdentifierState13"));
            provider.setOtherProviderIdentifierIssuer13(fieldSet.readString("otherProviderIdentifierIssuer13"));
            provider.setOtherProviderIdentifier14(fieldSet.readString("otherProviderIdentifier14"));
            provider.setOtherProviderIdentifierTypeCode14(fieldSet.readString("otherProviderIdentifierTypeCode14"));
            provider.setOtherProviderIdentifierState14(fieldSet.readString("otherProviderIdentifierState14"));
            provider.setOtherProviderIdentifierIssuer14(fieldSet.readString("otherProviderIdentifierIssuer14"));
            provider.setOtherProviderIdentifier15(fieldSet.readString("otherProviderIdentifier15"));
            provider.setOtherProviderIdentifierTypeCode15(fieldSet.readString("otherProviderIdentifierTypeCode15"));
            provider.setOtherProviderIdentifierState15(fieldSet.readString("otherProviderIdentifierState15"));
            provider.setOtherProviderIdentifierIssuer15(fieldSet.readString("otherProviderIdentifierIssuer15"));
            provider.setOtherProviderIdentifier16(fieldSet.readString("otherProviderIdentifier16"));
            provider.setOtherProviderIdentifierTypeCode16(fieldSet.readString("otherProviderIdentifierTypeCode16"));
            provider.setOtherProviderIdentifierState16(fieldSet.readString("otherProviderIdentifierState16"));
            provider.setOtherProviderIdentifierIssuer16(fieldSet.readString("otherProviderIdentifierIssuer16"));
            provider.setOtherProviderIdentifier17(fieldSet.readString("otherProviderIdentifier17"));
            provider.setOtherProviderIdentifierTypeCode17(fieldSet.readString("otherProviderIdentifierTypeCode17"));
            provider.setOtherProviderIdentifierState17(fieldSet.readString("otherProviderIdentifierState17"));
            provider.setOtherProviderIdentifierIssuer17(fieldSet.readString("otherProviderIdentifierIssuer17"));
            provider.setOtherProviderIdentifier18(fieldSet.readString("otherProviderIdentifier18"));
            provider.setOtherProviderIdentifierTypeCode18(fieldSet.readString("otherProviderIdentifierTypeCode18"));
            provider.setOtherProviderIdentifierState18(fieldSet.readString("otherProviderIdentifierState18"));
            provider.setOtherProviderIdentifierIssuer18(fieldSet.readString("otherProviderIdentifierIssuer18"));
            provider.setOtherProviderIdentifier19(fieldSet.readString("otherProviderIdentifier19"));
            provider.setOtherProviderIdentifierTypeCode19(fieldSet.readString("otherProviderIdentifierTypeCode19"));
            provider.setOtherProviderIdentifierState19(fieldSet.readString("otherProviderIdentifierState19"));
            provider.setOtherProviderIdentifierIssuer19(fieldSet.readString("otherProviderIdentifierIssuer19"));
            provider.setOtherProviderIdentifier20(fieldSet.readString("otherProviderIdentifier20"));
            provider.setOtherProviderIdentifierTypeCode20(fieldSet.readString("otherProviderIdentifierTypeCode20"));
            provider.setOtherProviderIdentifierState20(fieldSet.readString("otherProviderIdentifierState20"));
            provider.setOtherProviderIdentifierIssuer20(fieldSet.readString("otherProviderIdentifierIssuer20"));
            provider.setOtherProviderIdentifier21(fieldSet.readString("otherProviderIdentifier21"));
            provider.setOtherProviderIdentifierTypeCode21(fieldSet.readString("otherProviderIdentifierTypeCode21"));
            provider.setOtherProviderIdentifierState21(fieldSet.readString("otherProviderIdentifierState21"));
            provider.setOtherProviderIdentifierIssuer21(fieldSet.readString("otherProviderIdentifierIssuer21"));
            provider.setOtherProviderIdentifier22(fieldSet.readString("otherProviderIdentifier22"));
            provider.setOtherProviderIdentifierTypeCode22(fieldSet.readString("otherProviderIdentifierTypeCode22"));
            provider.setOtherProviderIdentifierState22(fieldSet.readString("otherProviderIdentifierState22"));
            provider.setOtherProviderIdentifierIssuer22(fieldSet.readString("otherProviderIdentifierIssuer22"));
            provider.setOtherProviderIdentifier23(fieldSet.readString("otherProviderIdentifier23"));
            provider.setOtherProviderIdentifierTypeCode23(fieldSet.readString("otherProviderIdentifierTypeCode23"));
            provider.setOtherProviderIdentifierState23(fieldSet.readString("otherProviderIdentifierState23"));
            provider.setOtherProviderIdentifierIssuer23(fieldSet.readString("otherProviderIdentifierIssuer23"));
            provider.setOtherProviderIdentifier24(fieldSet.readString("otherProviderIdentifier24"));
            provider.setOtherProviderIdentifierTypeCode24(fieldSet.readString("otherProviderIdentifierTypeCode24"));
            provider.setOtherProviderIdentifierState24(fieldSet.readString("otherProviderIdentifierState24"));
            provider.setOtherProviderIdentifierIssuer24(fieldSet.readString("otherProviderIdentifierIssuer24"));
            provider.setOtherProviderIdentifier25(fieldSet.readString("otherProviderIdentifier25"));
            provider.setOtherProviderIdentifierTypeCode25(fieldSet.readString("otherProviderIdentifierTypeCode25"));
            provider.setOtherProviderIdentifierState25(fieldSet.readString("otherProviderIdentifierState25"));
            provider.setOtherProviderIdentifierIssuer25(fieldSet.readString("otherProviderIdentifierIssuer25"));
            provider.setOtherProviderIdentifier26(fieldSet.readString("otherProviderIdentifier26"));
            provider.setOtherProviderIdentifierTypeCode26(fieldSet.readString("otherProviderIdentifierTypeCode26"));
            provider.setOtherProviderIdentifierState26(fieldSet.readString("otherProviderIdentifierState26"));
            provider.setOtherProviderIdentifierIssuer26(fieldSet.readString("otherProviderIdentifierIssuer26"));
            provider.setOtherProviderIdentifier27(fieldSet.readString("otherProviderIdentifier27"));
            provider.setOtherProviderIdentifierTypeCode27(fieldSet.readString("otherProviderIdentifierTypeCode27"));
            provider.setOtherProviderIdentifierState27(fieldSet.readString("otherProviderIdentifierState27"));
            provider.setOtherProviderIdentifierIssuer27(fieldSet.readString("otherProviderIdentifierIssuer27"));
            provider.setOtherProviderIdentifier28(fieldSet.readString("otherProviderIdentifier28"));
            provider.setOtherProviderIdentifierTypeCode28(fieldSet.readString("otherProviderIdentifierTypeCode28"));
            provider.setOtherProviderIdentifierState28(fieldSet.readString("otherProviderIdentifierState28"));
            provider.setOtherProviderIdentifierIssuer28(fieldSet.readString("otherProviderIdentifierIssuer28"));
            provider.setOtherProviderIdentifier29(fieldSet.readString("otherProviderIdentifier29"));
            provider.setOtherProviderIdentifierTypeCode29(fieldSet.readString("otherProviderIdentifierTypeCode29"));
            provider.setOtherProviderIdentifierState29(fieldSet.readString("otherProviderIdentifierState29"));
            provider.setOtherProviderIdentifierIssuer29(fieldSet.readString("otherProviderIdentifierIssuer29"));
            provider.setOtherProviderIdentifier30(fieldSet.readString("otherProviderIdentifier30"));
            provider.setOtherProviderIdentifierTypeCode30(fieldSet.readString("otherProviderIdentifierTypeCode30"));
            provider.setOtherProviderIdentifierState30(fieldSet.readString("otherProviderIdentifierState30"));
            provider.setOtherProviderIdentifierIssuer30(fieldSet.readString("otherProviderIdentifierIssuer30"));
            provider.setOtherProviderIdentifier31(fieldSet.readString("otherProviderIdentifier31"));
            provider.setOtherProviderIdentifierTypeCode31(fieldSet.readString("otherProviderIdentifierTypeCode31"));
            provider.setOtherProviderIdentifierState31(fieldSet.readString("otherProviderIdentifierState31"));
            provider.setOtherProviderIdentifierIssuer31(fieldSet.readString("otherProviderIdentifierIssuer31"));
            provider.setOtherProviderIdentifier32(fieldSet.readString("otherProviderIdentifier32"));
            provider.setOtherProviderIdentifierTypeCode32(fieldSet.readString("otherProviderIdentifierTypeCode32"));
            provider.setOtherProviderIdentifierState32(fieldSet.readString("otherProviderIdentifierState32"));
            provider.setOtherProviderIdentifierIssuer32(fieldSet.readString("otherProviderIdentifierIssuer32"));
            provider.setOtherProviderIdentifier33(fieldSet.readString("otherProviderIdentifier33"));
            provider.setOtherProviderIdentifierTypeCode33(fieldSet.readString("otherProviderIdentifierTypeCode33"));
            provider.setOtherProviderIdentifierState33(fieldSet.readString("otherProviderIdentifierState33"));
            provider.setOtherProviderIdentifierIssuer33(fieldSet.readString("otherProviderIdentifierIssuer33"));
            provider.setOtherProviderIdentifier34(fieldSet.readString("otherProviderIdentifier34"));
            provider.setOtherProviderIdentifierTypeCode34(fieldSet.readString("otherProviderIdentifierTypeCode34"));
            provider.setOtherProviderIdentifierState34(fieldSet.readString("otherProviderIdentifierState34"));
            provider.setOtherProviderIdentifierIssuer34(fieldSet.readString("otherProviderIdentifierIssuer34"));
            provider.setOtherProviderIdentifier35(fieldSet.readString("otherProviderIdentifier35"));
            provider.setOtherProviderIdentifierTypeCode35(fieldSet.readString("otherProviderIdentifierTypeCode35"));
            provider.setOtherProviderIdentifierState35(fieldSet.readString("otherProviderIdentifierState35"));
            provider.setOtherProviderIdentifierIssuer35(fieldSet.readString("otherProviderIdentifierIssuer35"));
            provider.setOtherProviderIdentifier36(fieldSet.readString("otherProviderIdentifier36"));
            provider.setOtherProviderIdentifierTypeCode36(fieldSet.readString("otherProviderIdentifierTypeCode36"));
            provider.setOtherProviderIdentifierState36(fieldSet.readString("otherProviderIdentifierState36"));
            provider.setOtherProviderIdentifierIssuer36(fieldSet.readString("otherProviderIdentifierIssuer36"));
            provider.setOtherProviderIdentifier37(fieldSet.readString("otherProviderIdentifier37"));
            provider.setOtherProviderIdentifierTypeCode37(fieldSet.readString("otherProviderIdentifierTypeCode37"));
            provider.setOtherProviderIdentifierState37(fieldSet.readString("otherProviderIdentifierState37"));
            provider.setOtherProviderIdentifierIssuer37(fieldSet.readString("otherProviderIdentifierIssuer37"));
            provider.setOtherProviderIdentifier38(fieldSet.readString("otherProviderIdentifier38"));
            provider.setOtherProviderIdentifierTypeCode38(fieldSet.readString("otherProviderIdentifierTypeCode38"));
            provider.setOtherProviderIdentifierState38(fieldSet.readString("otherProviderIdentifierState38"));
            provider.setOtherProviderIdentifierIssuer38(fieldSet.readString("otherProviderIdentifierIssuer38"));
            provider.setOtherProviderIdentifier39(fieldSet.readString("otherProviderIdentifier39"));
            provider.setOtherProviderIdentifierTypeCode39(fieldSet.readString("otherProviderIdentifierTypeCode39"));
            provider.setOtherProviderIdentifierState39(fieldSet.readString("otherProviderIdentifierState39"));
            provider.setOtherProviderIdentifierIssuer39(fieldSet.readString("otherProviderIdentifierIssuer39"));
            provider.setOtherProviderIdentifier40(fieldSet.readString("otherProviderIdentifier40"));
            provider.setOtherProviderIdentifierTypeCode40(fieldSet.readString("otherProviderIdentifierTypeCode40"));
            provider.setOtherProviderIdentifierState40(fieldSet.readString("otherProviderIdentifierState40"));
            provider.setOtherProviderIdentifierIssuer40(fieldSet.readString("otherProviderIdentifierIssuer40"));
            provider.setOtherProviderIdentifier41(fieldSet.readString("otherProviderIdentifier41"));
            provider.setOtherProviderIdentifierTypeCode41(fieldSet.readString("otherProviderIdentifierTypeCode41"));
            provider.setOtherProviderIdentifierState41(fieldSet.readString("otherProviderIdentifierState41"));
            provider.setOtherProviderIdentifierIssuer41(fieldSet.readString("otherProviderIdentifierIssuer41"));
            provider.setOtherProviderIdentifier42(fieldSet.readString("otherProviderIdentifier42"));
            provider.setOtherProviderIdentifierTypeCode42(fieldSet.readString("otherProviderIdentifierTypeCode42"));
            provider.setOtherProviderIdentifierState42(fieldSet.readString("otherProviderIdentifierState42"));
            provider.setOtherProviderIdentifierIssuer42(fieldSet.readString("otherProviderIdentifierIssuer42"));
            provider.setOtherProviderIdentifier43(fieldSet.readString("otherProviderIdentifier43"));
            provider.setOtherProviderIdentifierTypeCode43(fieldSet.readString("otherProviderIdentifierTypeCode43"));
            provider.setOtherProviderIdentifierState43(fieldSet.readString("otherProviderIdentifierState43"));
            provider.setOtherProviderIdentifierIssuer43(fieldSet.readString("otherProviderIdentifierIssuer43"));
            provider.setOtherProviderIdentifier44(fieldSet.readString("otherProviderIdentifier44"));
            provider.setOtherProviderIdentifierTypeCode44(fieldSet.readString("otherProviderIdentifierTypeCode44"));
            provider.setOtherProviderIdentifierState44(fieldSet.readString("otherProviderIdentifierState44"));
            provider.setOtherProviderIdentifierIssuer44(fieldSet.readString("otherProviderIdentifierIssuer44"));
            provider.setOtherProviderIdentifier45(fieldSet.readString("otherProviderIdentifier45"));
            provider.setOtherProviderIdentifierTypeCode45(fieldSet.readString("otherProviderIdentifierTypeCode45"));
            provider.setOtherProviderIdentifierState45(fieldSet.readString("otherProviderIdentifierState45"));
            provider.setOtherProviderIdentifierIssuer45(fieldSet.readString("otherProviderIdentifierIssuer45"));
            provider.setOtherProviderIdentifier46(fieldSet.readString("otherProviderIdentifier46"));
            provider.setOtherProviderIdentifierTypeCode46(fieldSet.readString("otherProviderIdentifierTypeCode46"));
            provider.setOtherProviderIdentifierState46(fieldSet.readString("otherProviderIdentifierState46"));
            provider.setOtherProviderIdentifierIssuer46(fieldSet.readString("otherProviderIdentifierIssuer46"));
            provider.setOtherProviderIdentifier47(fieldSet.readString("otherProviderIdentifier47"));
            provider.setOtherProviderIdentifierTypeCode47(fieldSet.readString("otherProviderIdentifierTypeCode47"));
            provider.setOtherProviderIdentifierState47(fieldSet.readString("otherProviderIdentifierState47"));
            provider.setOtherProviderIdentifierIssuer47(fieldSet.readString("otherProviderIdentifierIssuer47"));
            provider.setOtherProviderIdentifier48(fieldSet.readString("otherProviderIdentifier48"));
            provider.setOtherProviderIdentifierTypeCode48(fieldSet.readString("otherProviderIdentifierTypeCode48"));
            provider.setOtherProviderIdentifierState48(fieldSet.readString("otherProviderIdentifierState48"));
            provider.setOtherProviderIdentifierIssuer48(fieldSet.readString("otherProviderIdentifierIssuer48"));
            provider.setOtherProviderIdentifier49(fieldSet.readString("otherProviderIdentifier49"));
            provider.setOtherProviderIdentifierTypeCode49(fieldSet.readString("otherProviderIdentifierTypeCode49"));
            provider.setOtherProviderIdentifierState49(fieldSet.readString("otherProviderIdentifierState49"));
            provider.setOtherProviderIdentifierIssuer49(fieldSet.readString("otherProviderIdentifierIssuer49"));
            provider.setOtherProviderIdentifier50(fieldSet.readString("otherProviderIdentifier50"));
            provider.setOtherProviderIdentifierTypeCode50(fieldSet.readString("otherProviderIdentifierTypeCode50"));
            provider.setOtherProviderIdentifierState50(fieldSet.readString("otherProviderIdentifierState50"));
            provider.setOtherProviderIdentifierIssuer50(fieldSet.readString("otherProviderIdentifierIssuer50"));
            provider.setSoleProprietorFlag(fieldSet.readString("soleProprietorFlag"));
            provider.setOrganizationSubpartFlag(fieldSet.readString("organizationSubpartFlag"));
            provider.setParentOrganizationLegalBusinessName(fieldSet.readString("parentOrganizationLegalBusinessName"));
            provider.setParentOrganizationTin(fieldSet.readString("parentOrganizationTin"));
            provider.setAuthorizedOfficialNamePrefixText(fieldSet.readString("authorizedOfficialNamePrefixText"));
            provider.setAuthorizedOfficialNameSuffixText(fieldSet.readString("authorizedOfficialNameSuffixText"));
            provider.setAuthorizedOfficialCredentialText(fieldSet.readString("authorizedOfficialCredentialText"));
            provider.setHealthcareProviderTaxonomyGroup1(fieldSet.readString("healthcareProviderTaxonomyGroup1"));
            provider.setHealthcareProviderTaxonomyGroup2(fieldSet.readString("healthcareProviderTaxonomyGroup2"));
            provider.setHealthcareProviderTaxonomyGroup3(fieldSet.readString("healthcareProviderTaxonomyGroup3"));
            provider.setHealthcareProviderTaxonomyGroup4(fieldSet.readString("healthcareProviderTaxonomyGroup4"));
            provider.setHealthcareProviderTaxonomyGroup5(fieldSet.readString("healthcareProviderTaxonomyGroup5"));
            provider.setHealthcareProviderTaxonomyGroup6(fieldSet.readString("healthcareProviderTaxonomyGroup6"));
            provider.setHealthcareProviderTaxonomyGroup7(fieldSet.readString("healthcareProviderTaxonomyGroup7"));
            provider.setHealthcareProviderTaxonomyGroup8(fieldSet.readString("healthcareProviderTaxonomyGroup8"));
            provider.setHealthcareProviderTaxonomyGroup9(fieldSet.readString("healthcareProviderTaxonomyGroup9"));
            provider.setHealthcareProviderTaxonomyGroup10(fieldSet.readString("healthcareProviderTaxonomyGroup10"));
            provider.setHealthcareProviderTaxonomyGroup11(fieldSet.readString("healthcareProviderTaxonomyGroup11"));
            provider.setHealthcareProviderTaxonomyGroup12(fieldSet.readString("healthcareProviderTaxonomyGroup12"));
            provider.setHealthcareProviderTaxonomyGroup13(fieldSet.readString("healthcareProviderTaxonomyGroup13"));
            provider.setHealthcareProviderTaxonomyGroup14(fieldSet.readString("healthcareProviderTaxonomyGroup14"));
            provider.setHealthcareProviderTaxonomyGroup15(fieldSet.readString("healthcareProviderTaxonomyGroup15"));
            return provider;
        });
        return lineMapper;
    }

    @Bean
    public DelimitedLineTokenizer providerLineTokenizer() {
        DelimitedLineTokenizer delimitedLineTokenizer = new DelimitedLineTokenizer();
        String[] providerFields = {
                "npi",
                "entityTypeCode",
                "replacementNpi",
                "employerIdentificationNumber",
                "providerOrganizationName",
                "providerLastName",
                "providerFirstName",
                "providerMiddleName",
                "providerNamePrefixText",
                "providerNameSuffixText",
                "providerCredentialText",
                "providerOtherOrganizationName",
                "providerOtherOrganizationNameTypeCode",
                "providerOtherLastName",
                "providerOtherFirstName",
                "providerOtherMiddleName",
                "providerOtherNamePrefixText",
                "providerOtherNameSuffixText",
                "providerOtherCredentialText",
                "providerOtherLastNameTypeCode",
                "providerFirstLineBusinessMailingAddress",
                "providerSecondLineBusinessMailingAddress",
                "providerBusinessMailingAddressCityName",
                "providerBusinessMailingAddressStateName",
                "providerBusinessMailingAddressPostalCode",
                "providerBusinessMailingAddressCountryCode",
                "providerBusinessMailingAddressTelephoneNumber",
                "providerBusinessMailingAddressFaxNumber",
                "providerFirstLineBusinessPracticeLocationAddress",
                "providerSecondLineBusinessPracticeLocationAddress",
                "providerBusinessPracticeLocationAddressCityName",
                "providerBusinessPracticeLocationAddressStateName",
                "providerBusinessPracticeLocationAddressPostalCode",
                "providerBusinessPracticeLocationAddressCountryCode",
                "providerBusinessPracticeLocationAddressTelephoneNumber",
                "providerBusinessPracticeLocationAddressFaxNumber",
                "providerEnumerationDate",
                "lastUpdateDate",
                "npiDeactivationReasonCode",
                "deactivationDate",
                "reactivationDate",
                "providerGenderCode",
                "authorizedOfficialLastName",
                "authorizedOfficialFirstName",
                "authorizedOfficialMiddleName",
                "authorizedOfficialTitle",
                "authorizedOfficialTelephoneNumber",
                "healthcareProviderTaxonomyCode1",
                "providerLicenseNumber1",
                "providerLicenseNumberStateCode1",
                "healthcareProviderPrimaryTaxonomySwitch1",
                "healthcareProviderTaxonomyCode2",
                "providerLicenseNumber2",
                "providerLicenseNumberStateCode2",
                "healthcareProviderPrimaryTaxonomySwitch2",
                "healthcareProviderTaxonomyCode3",
                "providerLicenseNumber3",
                "providerLicenseNumberStateCode3",
                "healthcareProviderPrimaryTaxonomySwitch3",
                "healthcareProviderTaxonomyCode4",
                "providerLicenseNumber4",
                "providerLicenseNumberStateCode4",
                "healthcareProviderPrimaryTaxonomySwitch4",
                "healthcareProviderTaxonomyCode5",
                "providerLicenseNumber5",
                "providerLicenseNumberStateCode5",
                "healthcareProviderPrimaryTaxonomySwitch5",
                "healthcareProviderTaxonomyCode6",
                "providerLicenseNumber6",
                "providerLicenseNumberStateCode6",
                "healthcareProviderPrimaryTaxonomySwitch6",
                "healthcareProviderTaxonomyCode7",
                "providerLicenseNumber7",
                "providerLicenseNumberStateCode7",
                "healthcareProviderPrimaryTaxonomySwitch7",
                "healthcareProviderTaxonomyCode8",
                "providerLicenseNumber8",
                "providerLicenseNumberStateCode8",
                "healthcareProviderPrimaryTaxonomySwitch8",
                "healthcareProviderTaxonomyCode9",
                "providerLicenseNumber9",
                "providerLicenseNumberStateCode9",
                "healthcareProviderPrimaryTaxonomySwitch9",
                "healthcareProviderTaxonomyCode10",
                "providerLicenseNumber10",
                "providerLicenseNumberStateCode10",
                "healthcareProviderPrimaryTaxonomySwitch10",
                "healthcareProviderTaxonomyCode11",
                "providerLicenseNumber11",
                "providerLicenseNumberStateCode11",
                "healthcareProviderPrimaryTaxonomySwitch11",
                "healthcareProviderTaxonomyCode12",
                "providerLicenseNumber12",
                "providerLicenseNumberStateCode12",
                "healthcareProviderPrimaryTaxonomySwitch12",
                "healthcareProviderTaxonomyCode13",
                "providerLicenseNumber13",
                "providerLicenseNumberStateCode13",
                "healthcareProviderPrimaryTaxonomySwitch13",
                "healthcareProviderTaxonomyCode14",
                "providerLicenseNumber14",
                "providerLicenseNumberStateCode14",
                "healthcareProviderPrimaryTaxonomySwitch14",
                "healthcareProviderTaxonomyCode15",
                "providerLicenseNumber15",
                "providerLicenseNumberStateCode15",
                "healthcareProviderPrimaryTaxonomySwitch15",
                "otherProviderIdentifier1",
                "otherProviderIdentifierTypeCode1",
                "otherProviderIdentifierState1",
                "otherProviderIdentifierIssuer1",
                "otherProviderIdentifier2",
                "otherProviderIdentifierTypeCode2",
                "otherProviderIdentifierState2",
                "otherProviderIdentifierIssuer2",
                "otherProviderIdentifier3",
                "otherProviderIdentifierTypeCode3",
                "otherProviderIdentifierState3",
                "otherProviderIdentifierIssuer3",
                "otherProviderIdentifier4",
                "otherProviderIdentifierTypeCode4",
                "otherProviderIdentifierState4",
                "otherProviderIdentifierIssuer4",
                "otherProviderIdentifier5",
                "otherProviderIdentifierTypeCode5",
                "otherProviderIdentifierState5",
                "otherProviderIdentifierIssuer5",
                "otherProviderIdentifier6",
                "otherProviderIdentifierTypeCode6",
                "otherProviderIdentifierState6",
                "otherProviderIdentifierIssuer6",
                "otherProviderIdentifier7",
                "otherProviderIdentifierTypeCode7",
                "otherProviderIdentifierState7",
                "otherProviderIdentifierIssuer7",
                "otherProviderIdentifier8",
                "otherProviderIdentifierTypeCode8",
                "otherProviderIdentifierState8",
                "otherProviderIdentifierIssuer8",
                "otherProviderIdentifier9",
                "otherProviderIdentifierTypeCode9",
                "otherProviderIdentifierState9",
                "otherProviderIdentifierIssuer9",
                "otherProviderIdentifier10",
                "otherProviderIdentifierTypeCode10",
                "otherProviderIdentifierState10",
                "otherProviderIdentifierIssuer10",
                "otherProviderIdentifier11",
                "otherProviderIdentifierTypeCode11",
                "otherProviderIdentifierState11",
                "otherProviderIdentifierIssuer11",
                "otherProviderIdentifier12",
                "otherProviderIdentifierTypeCode12",
                "otherProviderIdentifierState12",
                "otherProviderIdentifierIssuer12",
                "otherProviderIdentifier13",
                "otherProviderIdentifierTypeCode13",
                "otherProviderIdentifierState13",
                "otherProviderIdentifierIssuer13",
                "otherProviderIdentifier14",
                "otherProviderIdentifierTypeCode14",
                "otherProviderIdentifierState14",
                "otherProviderIdentifierIssuer14",
                "otherProviderIdentifier15",
                "otherProviderIdentifierTypeCode15",
                "otherProviderIdentifierState15",
                "otherProviderIdentifierIssuer15",
                "otherProviderIdentifier16",
                "otherProviderIdentifierTypeCode16",
                "otherProviderIdentifierState16",
                "otherProviderIdentifierIssuer16",
                "otherProviderIdentifier17",
                "otherProviderIdentifierTypeCode17",
                "otherProviderIdentifierState17",
                "otherProviderIdentifierIssuer17",
                "otherProviderIdentifier18",
                "otherProviderIdentifierTypeCode18",
                "otherProviderIdentifierState18",
                "otherProviderIdentifierIssuer18",
                "otherProviderIdentifier19",
                "otherProviderIdentifierTypeCode19",
                "otherProviderIdentifierState19",
                "otherProviderIdentifierIssuer19",
                "otherProviderIdentifier20",
                "otherProviderIdentifierTypeCode20",
                "otherProviderIdentifierState20",
                "otherProviderIdentifierIssuer20",
                "otherProviderIdentifier21",
                "otherProviderIdentifierTypeCode21",
                "otherProviderIdentifierState21",
                "otherProviderIdentifierIssuer21",
                "otherProviderIdentifier22",
                "otherProviderIdentifierTypeCode22",
                "otherProviderIdentifierState22",
                "otherProviderIdentifierIssuer22",
                "otherProviderIdentifier23",
                "otherProviderIdentifierTypeCode23",
                "otherProviderIdentifierState23",
                "otherProviderIdentifierIssuer23",
                "otherProviderIdentifier24",
                "otherProviderIdentifierTypeCode24",
                "otherProviderIdentifierState24",
                "otherProviderIdentifierIssuer24",
                "otherProviderIdentifier25",
                "otherProviderIdentifierTypeCode25",
                "otherProviderIdentifierState25",
                "otherProviderIdentifierIssuer25",
                "otherProviderIdentifier26",
                "otherProviderIdentifierTypeCode26",
                "otherProviderIdentifierState26",
                "otherProviderIdentifierIssuer26",
                "otherProviderIdentifier27",
                "otherProviderIdentifierTypeCode27",
                "otherProviderIdentifierState27",
                "otherProviderIdentifierIssuer27",
                "otherProviderIdentifier28",
                "otherProviderIdentifierTypeCode28",
                "otherProviderIdentifierState28",
                "otherProviderIdentifierIssuer28",
                "otherProviderIdentifier29",
                "otherProviderIdentifierTypeCode29",
                "otherProviderIdentifierState29",
                "otherProviderIdentifierIssuer29",
                "otherProviderIdentifier30",
                "otherProviderIdentifierTypeCode30",
                "otherProviderIdentifierState30",
                "otherProviderIdentifierIssuer30",
                "otherProviderIdentifier31",
                "otherProviderIdentifierTypeCode31",
                "otherProviderIdentifierState31",
                "otherProviderIdentifierIssuer31",
                "otherProviderIdentifier32",
                "otherProviderIdentifierTypeCode32",
                "otherProviderIdentifierState32",
                "otherProviderIdentifierIssuer32",
                "otherProviderIdentifier33",
                "otherProviderIdentifierTypeCode33",
                "otherProviderIdentifierState33",
                "otherProviderIdentifierIssuer33",
                "otherProviderIdentifier34",
                "otherProviderIdentifierTypeCode34",
                "otherProviderIdentifierState34",
                "otherProviderIdentifierIssuer34",
                "otherProviderIdentifier35",
                "otherProviderIdentifierTypeCode35",
                "otherProviderIdentifierState35",
                "otherProviderIdentifierIssuer35",
                "otherProviderIdentifier36",
                "otherProviderIdentifierTypeCode36",
                "otherProviderIdentifierState36",
                "otherProviderIdentifierIssuer36",
                "otherProviderIdentifier37",
                "otherProviderIdentifierTypeCode37",
                "otherProviderIdentifierState37",
                "otherProviderIdentifierIssuer37",
                "otherProviderIdentifier38",
                "otherProviderIdentifierTypeCode38",
                "otherProviderIdentifierState38",
                "otherProviderIdentifierIssuer38",
                "otherProviderIdentifier39",
                "otherProviderIdentifierTypeCode39",
                "otherProviderIdentifierState39",
                "otherProviderIdentifierIssuer39",
                "otherProviderIdentifier40",
                "otherProviderIdentifierTypeCode40",
                "otherProviderIdentifierState40",
                "otherProviderIdentifierIssuer40",
                "otherProviderIdentifier41",
                "otherProviderIdentifierTypeCode41",
                "otherProviderIdentifierState41",
                "otherProviderIdentifierIssuer41",
                "otherProviderIdentifier42",
                "otherProviderIdentifierTypeCode42",
                "otherProviderIdentifierState42",
                "otherProviderIdentifierIssuer42",
                "otherProviderIdentifier43",
                "otherProviderIdentifierTypeCode43",
                "otherProviderIdentifierState43",
                "otherProviderIdentifierIssuer43",
                "otherProviderIdentifier44",
                "otherProviderIdentifierTypeCode44",
                "otherProviderIdentifierState44",
                "otherProviderIdentifierIssuer44",
                "otherProviderIdentifier45",
                "otherProviderIdentifierTypeCode45",
                "otherProviderIdentifierState45",
                "otherProviderIdentifierIssuer45",
                "otherProviderIdentifier46",
                "otherProviderIdentifierTypeCode46",
                "otherProviderIdentifierState46",
                "otherProviderIdentifierIssuer46",
                "otherProviderIdentifier47",
                "otherProviderIdentifierTypeCode47",
                "otherProviderIdentifierState47",
                "otherProviderIdentifierIssuer47",
                "otherProviderIdentifier48",
                "otherProviderIdentifierTypeCode48",
                "otherProviderIdentifierState48",
                "otherProviderIdentifierIssuer48",
                "otherProviderIdentifier49",
                "otherProviderIdentifierTypeCode49",
                "otherProviderIdentifierState49",
                "otherProviderIdentifierIssuer49",
                "otherProviderIdentifier50",
                "otherProviderIdentifierTypeCode50",
                "otherProviderIdentifierState50",
                "otherProviderIdentifierIssuer50",
                "soleProprietorFlag",
                "organizationSubpartFlag",
                "parentOrganizationLegalBusinessName",
                "parentOrganizationTin",
                "authorizedOfficialNamePrefixText",
                "authorizedOfficialNameSuffixText",
                "authorizedOfficialCredentialText",
                "healthcareProviderTaxonomyGroup1",
                "healthcareProviderTaxonomyGroup2",
                "healthcareProviderTaxonomyGroup3",
                "healthcareProviderTaxonomyGroup4",
                "healthcareProviderTaxonomyGroup5",
                "healthcareProviderTaxonomyGroup6",
                "healthcareProviderTaxonomyGroup7",
                "healthcareProviderTaxonomyGroup8",
                "healthcareProviderTaxonomyGroup9",
                "healthcareProviderTaxonomyGroup10",
                "healthcareProviderTaxonomyGroup11",
                "healthcareProviderTaxonomyGroup12",
                "healthcareProviderTaxonomyGroup13",
                "healthcareProviderTaxonomyGroup14",
                "healthcareProviderTaxonomyGroup15"
        };
        delimitedLineTokenizer.setNames(providerFields);
        return delimitedLineTokenizer;
    }

    @Bean
    public RepositoryItemWriter<Provider> providerWriter(ProviderRepository providerRepository) {
        RepositoryItemWriter<Provider> writer = new RepositoryItemWriter<>();
        writer.setRepository(providerRepository);
        writer.setMethodName("save");
        return writer;
    }
}
